ios_banner - Bugfix for presence of multiple delimitation chars in the banner's declaration (#433)
ios_banner - Bugfix for presence of multiple delimitation chars in the banner's declaration

SUMMARY
Implementation of more dynamic banner regex string matching to address edge cases of multiple 'C' delimitation characters that may be present in the banner declaration within the device's configuration.
ISSUE TYPE

Bugfix Pull Request

COMPONENT NAME
ios_banner.py
ADDITIONAL INFORMATION
For cases where more than one 'C' delimitation char is present in the device running configuration 'banner <banner_type>' declaration line e.g. '^CCC'.
For example, the running device configuration case of:
banner login ^CCC
test
^C

BEFORE: When an ios_banner present task is called, this results in the following IndexError, as split() has a static string (not a regex) passed into it, ending with ' ^C\n', causing the split to not function as desired when multiple 'C' delimitation chars present, as it does not cause a match:
ansible_collections/cisco/ios/plugins/modules/ios_banner.py\", line 150, in map_config_to_obj
IndexError: list index out of range

AFTER: The fix implementation, where we first pull out a string match with a regex to accommodate the presence of multiple 'C' delimiters, then pass this regex string match into the split function:
EXEC /bin/sh -c '/usr/bin/python3 .ansible/tmp/ansible-local-2108ui6dkvh_/ansible-tmp-1633187470.7116272-2146-30692676631387/AnsiballZ_ios_banner.py && sleep 0'

changed: [x.x.x.x] => {
    "changed": true,
    "commands": [
        "banner login @\nNEW BANNER\n@"
    ],
    "invocation": {
        "module_args": {
            "banner": "login",
            "multiline_delimiter": "@",
            "provider": null,
            "state": "present",
            "text": "NEW BANNER\n"
        }
    }
}

Reviewed-by: Sagar Paul <sagpaul@redhat.com>
Reviewed-by: None <None>